### ISSUE TITLE
Migrate Dockerfile from container-dtc-metviewer to the METviewer repository.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METviewer#166]
## Describe the Task ##

- Migrate Dockerfile from container-dtc-metviewer (https://github.com/dtcenter/container-dtc-metviewer/tree/master/METviewer) to the METviewer repository itself.
- Once completed, delete the container-dtc-metviewer repository.
- Update the DockerHub METviewer settings (https://hub.docker.com/repository/docker/dtcenter/metviewer/builds) to watch the GitHub METviewer repository.
- Define automated build rules to automatically create/update images for specific branches and retags, similar to the setup for MET (https://hub.docker.com/repository/docker/dtcenter/met/builds/edit).

This setup works much better because anytime the METviewer repo changes (i.e. new development on the develop branch, bugfixes on the master_vX.Y branches, or new release tags), DockerHub will create or rebuild the associated image.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I made a lot of progress on this today with help from Tatiana. All changes are on the branch named feature_166_docker.
- Added docker directory containing the Dockerfile to build the METviewer image and docker-compose.yml to bring it up.
- Modified the Dockerfile to pull METcalcpy, METplotpy, and METviewer from GitHub instead of a pre-built tarball.
- Modified the Dockerfile to build/install METviewer.
- Setup DockerHub to watch the Dockerfile in github.com/dtcenter/METviewer and trigger automated builds for the feature_166_docker branch.
- Added a docker/hooks/build file to specify the version of METcalcpy, METplotpy, and METviewer to be built.
- Add a docker/.env file to specify the version of METviewer to be pulled/run.
- Updated the Dockerfile to NOT overwrite /usr/bin/python with python3. Instead, create /usr/local/bin/python as a soft link to /usr/bin/python3 and update the Dockefile to use that version. Tested and it works.

Remaining work:
- Consider finding/adding test_load.xml to the repo and stashing it in /METviewer/xml/test_load.xml inside the image.
- Figure out how to *easily* load user's data into a local METviewer instance.
- Once everything is working well, work on DockerHub's automated build rules. Create containers for master_v3.1 (tagged as master_3.1 and latest) as well as the develop branch (tagged as develop).
- Consider deleting the METviewer master branch and making master_v3.1 the new default branch.

Do not do this yet:
- Consider cleaning up the /METviewer directory after it's been built (e.g. compare /METviewer contents between dtcenter/METviewer:3.1 (clean) and dtcenter/METviewer:feature_166 (not clean)). Don't do this now since it may be useful to have the entire repo present for additional development within the container. Could use the same logic as with MET... for released tags, clean up... for development branches, do not.

**Comment by JohnHalleyGotway** [comment]
After getting direction from Tatiana, I renamed master_v3.1 to main_v3.1 and set it as the new default branch.
I also deleted the master branch and replaced master with main in the GitHub issue templates on the main_v3.1 and develop branches.

**Comment by JohnHalleyGotway** [comment]
Configure automated builds on DockerHub for main_v3.1 (latest), develop, main_v* branches, and v* tags.
https://hub.docker.com/repository/docker/dtcenter/metviewer/builds
