### ISSUE TITLE
Adjust SonarQube for "false positive" METviewer vulnerabilities

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METviewer#547]
## Describe the Task ##
SonarQube is identifying vulnerabilities in code where it is clear that exceptions are correctly caught and handled.  The vulnerabilities are all found in the **MVServlet.java** code for the **doPost() method**.  Originally, there were 15 vulnerabilities identified by SonarQube, and after applying the suggested fixes, 10 different vulnerabilities are  now identified as a result of these "fixes".

It appears that these are false-positives, as the code in question is surrounded by a try-catch block that specifically handles the thrown exception.  This screen shot illustrates that the _strResp.append(handleListVal(nodeCall, requestBody.toString(), currentDbName));_ is wrapped in a try-catch block that specifically catches the ParserConfigurationException- _note the catch block under the "Handle the following exception that could be thrown by "handleListVal":ParserConfigurationException_.

<img width="987" alt="Screenshot 2024-08-22 at 4 46 44 PM" src="https://github.com/user-attachments/assets/55fc391f-ae21-4d09-a7cb-082d9d6a2d4d">

The code has nested try-catch blocks and the parent/outermost try-catch block will catch all of the exceptions thrown in the nested try-catch blocks if the exceptions aren't handled within these nested blocks. As a result, NO exceptions should be left unhandled.  Tatiana Burek verified that the fixes appear to be correct. 

 The interface has options to allow you to "Resolve as Fixed", "Resolve as False Positive", or "Resolve as won't fix", but they do not appear to have any effect.  Determine if there are SonarQube settings to resolve these 'false positives'. 
### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METviewer-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METviewer-X.Y.Z** version, select the **METviewer-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METviewer-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Hi @bikegeek.  This issue can be resolved.  Attached are two screenshots and a video.  One screenshot shows the 10 vulnerabilities that existed.  The video demonstrates how I selected "Resolve as False Positive".  The additional screenshots shows the resulting 0 vulnerabilities.  Because there is no change to the code, this issue will not have a PR and will just be Closed with this comment.
<img width="1761" alt="Screen Shot 2024-08-27 at 11 32 25 AM" src="https://github.com/user-attachments/assets/7ff42c13-937b-4371-8aa1-32af5b0e874c">

https://github.com/user-attachments/assets/13ffb0aa-e77f-406c-87b2-e79c0bd6e846

<img width="1783" alt="Screen Shot 2024-08-27 at 11 32 54 AM" src="https://github.com/user-attachments/assets/50e2a216-038e-4c9c-ab73-5ebe0bad9671">
